# Generated by Django 4.1.7 on 2023-03-14 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 21, 24, 38, 675927)),
        ),
    ]
