# Generated by Django 4.1.7 on 2023-03-16 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_answer_answer_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='time_pub',
        ),
        migrations.AddField(
            model_name='answer',
            name='time_public',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 19, 9, 1, 737493)),
        ),
        migrations.AddField(
            model_name='question',
            name='time_public',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 19, 9, 1, 684613)),
        ),
    ]
